version: '3.7'
services:
  production:
    container_name: noclegi
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx/default.conf:/etc/nginx/sites-available/default