# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: landing
    steps:
    - uses: actions/checkout@v2
    - name: Docker Deploy
      uses: actions/setup-node@v2
    - run: docker-compose -f docker-compose.prod.yml up -d --build
